<x-main-layout>
    <x-slot name="title"> Aviso legal </x-slot>

    <!-- Sobre nosotros -->
    <section class="container mx-auto py-4 bg-yellow-100 rounded-t-3xl rounded-r-3xl mt-6">
        <h1 class="text-4xl text-center font-poppinsBlack py-4">Aviso legal</h1>
    </section>

    <div x-data="{ activeTab:  1 }" class="container mx-auto grid grid-cols-1 md:grid-cols-3 lg:grid-cols-4 bg-white gap-4 p-2 lg:p-8 xl:p-20 rounded-b-3xl">
        <div class="flex justify-center">
            <div class="w-full mx-auto md:px-0 sm:px-4">
                <ul class="space-y-3">
                    <li @click="activeTab = 1" :class="{ 'bg-primary text-white': activeTab === 1 }" class="bg-gray-300 p-3 hover:cursor-pointer">Condiciones de uso</li>
                    <li @click="activeTab = 2" :class="{ 'bg-primary text-white': activeTab === 2 }" class="bg-gray-300 p-3 hover:cursor-pointer">Aviso legal</li>
                    <li @click="activeTab = 3" :class="{ 'bg-primary text-white': activeTab === 3 }" class="bg-gray-300 p-3 hover:cursor-pointer">Política de privacidad</li>
                    <li @click="activeTab = 4" :class="{ 'bg-primary text-white': activeTab === 4 }" class="bg-gray-300 p-3 hover:cursor-pointer">Política de cookies</li>
                </ul>
            </div>
        </div>
        <div class="bg-white col-span-1 md:col-span-2 lg:col-span-3 p-2 text-justify">
            <div class="px-2" x-collapse x-cloak x-show="activeTab === 1">
                <h2 class="font-poppinsBlack m-2 text-2xl">Condiciones de uso</h2>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ipsum nisi, posuere ac mattis sed, tempus non sem. Sed sit amet dolor id eros lacinia posuere. Phasellus lobortis est quis purus lobortis faucibus ac ac magna. Sed non volutpat dolor. Donec posuere risus eu purus vestibulum efficitur. Aenean in lorem fringilla, luctus dui non, iaculis erat. Curabitur ac fringilla nibh, et vehicula est. Etiam ut felis lacinia elit sodales vulputate et vel lectus. Nullam consectetur sapien a nulla tincidunt, non sollicitudin augue dictum. Phasellus sit amet ornare ex. Aliquam sit amet tincidunt velit. Vestibulum luctus id mauris in laoreet. Ut ut ligula sit amet lacus congue suscipit ac a sem. Nullam posuere, sapien ut placerat pulvinar, ante urna ultricies felis, sit amet mattis lorem enim vitae nisl. Cras sodales nibh a nisl maximus porta. Quisque luctus sed velit in luctus. In nec imperdiet mi. Ut vitae ligula massa. Proin interdum, nibh vitae tincidunt sodales, nibh sapien finibus odio, sed sagittis mauris tellus eu ex. Pellentesque pellentesque ultricies luctus. Aenean massa est, consectetur sed turpis sed, semper hendrerit mauris. Suspendisse eu consectetur ipsum. Integer molestie lobortis risus, sit amet luctus lacus. Sed volutpat commodo dolor, eget feugiat elit molestie a. Quisque odio felis, fringilla at congue sit amet, blandit at eros. Aenean tincidunt nunc eu eleifend bibendum. Vestibulum venenatis nibh iaculis, pharetra odio a, dapibus nunc. Donec eget arcu quis neque vulputate tempor. Etiam tincidunt scelerisque justo non tincidunt. Proin tincidunt mi non sapien eleifend vulputate. Ut varius libero et lectus vulputate sodales. Integer blandit erat nec quam mollis mattis. In semper dictum finibus. Vestibulum sed dictum sapien, sed accumsan magna. Vestibulum sodales elementum leo sed cursus. Curabitur sit amet semper odio. Curabitur ultricies lacus risus, ac suscipit purus vulputate sit amet. Integer porttitor, velit at feugiat volutpat, metus ligula rhoncus est, vel porttitor sem est quis odio. Donec eget porttitor orci, nec mattis dolor. Aliquam eget scelerisque nulla, quis aliquet augue. Vivamus volutpat aliquet massa, vel egestas dui ornare vel. Donec euismod neque non sollicitudin sodales. Ut quis lorem nibh. Praesent rhoncus libero aliquet interdum varius. Phasellus aliquet diam eget lectus dictum, vel porttitor turpis suscipit. Ut cursus sapien nec tristique tincidunt. Integer semper facilisis imperdiet. Aliquam eleifend a magna in congue. Vivamus quis orci scelerisque, finibus arcu eu, lacinia turpis. Donec at ultricies nulla. Quisque eget gravida sem, viverra dapibus ipsum.
            </div>
            <div class="px-2" x-collapse x-cloak x-show="activeTab === 2">
                <h2 class="font-poppinsBlack m-2 text-2xl">Aviso legal</h2>
                Sed eget lacus tincidunt, ornare mauris vitae, ullamcorper tellus. Vestibulum mollis ante vel tellus commodo pretium. Nulla vel blandit nisl, a sodales augue. Quisque porttitor in justo rutrum scelerisque. Donec rutrum est eros, eget laoreet eros placerat quis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris sit amet feugiat leo. Donec imperdiet blandit quam quis porta. Integer sem orci, tincidunt non sem at, interdum pulvinar risus. Cras tempor mollis massa, vel sodales felis pellentesque nec. In eu mauris interdum, laoreet ipsum vel, sodales dolor. Quisque luctus sapien nisi, at consectetur urna rhoncus in. Etiam suscipit eros vestibulum sollicitudin lobortis. Donec sed dui sit amet neque interdum vulputate in vel mi. Cras eleifend lectus et pulvinar finibus. Fusce vestibulum purus id sagittis feugiat. Nunc ultrices dignissim felis, nec pharetra tellus hendrerit ac. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur sit amet nunc at odio mollis venenatis. Morbi porttitor felis vel mi eleifend, vel tincidunt odio semper. Vestibulum ornare tempus augue, in bibendum nibh fringilla ut. Nunc mollis sollicitudin nulla, eget pellentesque purus elementum ac. Donec laoreet massa dui, ut semper libero rutrum pulvinar. Maecenas ut imperdiet nisl, vel mattis nulla. Integer interdum condimentum placerat. Sed consectetur condimentum eros, at porttitor orci scelerisque id. Duis venenatis eros nec aliquam luctus. Fusce nec nisi finibus felis dignissim consectetur. Proin sed orci nibh. Praesent justo nibh, rutrum vitae magna molestie, hendrerit vestibulum neque. Pellentesque ornare sit amet nisl at porta. Nunc quis felis purus. Nam accumsan purus ac tristique lobortis. Praesent tincidunt pulvinar elementum. Nullam efficitur fringilla sagittis. Morbi varius porttitor fermentum. Praesent fermentum, erat semper gravida volutpat, sem mi condimentum est, ac scelerisque massa orci ac elit. Nunc ullamcorper pellentesque efficitur. Mauris vel tellus ut massa dapibus tempor congue in massa. Phasellus ut facilisis massa, eu egestas tortor. Donec sit amet erat neque. Sed eu velit aliquet, sagittis lectus id, semper ipsum. Fusce turpis orci, pharetra eget euismod ut, viverra ut purus. Nullam faucibus nulla erat, id facilisis lectus tristique nec. Pellentesque scelerisque tincidunt ex, sed egestas dui mattis vitae. Nunc congue purus vitae nisl fermentum pulvinar. Pellentesque hendrerit nisl in est tempor, eget eleifend lacus fermentum. Pellentesque faucibus quam tristique orci placerat, eget iaculis nisi pellentesque. Donec tincidunt interdum ligula vitae ornare. Sed magna purus, pharetra id rutrum non, pellentesque id dui. Donec pellentesque neque tristique purus sodales, porta pharetra arcu eleifend. Nulla a sagittis nunc. Praesent maximus urna at condimentum ullamcorper. Pellentesque in libero tortor. Nullam dignissim leo nec dictum tempus.
            </div>
            <div class="px-2" x-collapse x-cloak x-show="activeTab === 3">
                <h2 class="font-poppinsBlack m-2 text-2xl">Política de privacidad</h2>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ipsum nisi, posuere ac mattis sed, tempus non sem. Sed sit amet dolor id eros lacinia posuere. Phasellus lobortis est quis purus lobortis faucibus ac ac magna. Sed non volutpat dolor. Donec posuere risus eu purus vestibulum efficitur. Aenean in lorem fringilla, luctus dui non, iaculis erat. Curabitur ac fringilla nibh, et vehicula est. Etiam ut felis lacinia elit sodales vulputate et vel lectus. Nullam consectetur sapien a nulla tincidunt, non sollicitudin augue dictum. Phasellus sit amet ornare ex. Aliquam sit amet tincidunt velit. Vestibulum luctus id mauris in laoreet. Ut ut ligula sit amet lacus congue suscipit ac a sem. Nullam posuere, sapien ut placerat pulvinar, ante urna ultricies felis, sit amet mattis lorem enim vitae nisl. Cras sodales nibh a nisl maximus porta. Quisque luctus sed velit in luctus. In nec imperdiet mi. Ut vitae ligula massa. Proin interdum, nibh vitae tincidunt sodales, nibh sapien finibus odio, sed sagittis mauris tellus eu ex. Pellentesque pellentesque ultricies luctus. Aenean massa est, consectetur sed turpis sed, semper hendrerit mauris. Suspendisse eu consectetur ipsum. Integer molestie lobortis risus, sit amet luctus lacus. Sed volutpat commodo dolor, eget feugiat elit molestie a. Quisque odio felis, fringilla at congue sit amet, blandit at eros. Aenean tincidunt nunc eu eleifend bibendum. Vestibulum venenatis nibh iaculis, pharetra odio a, dapibus nunc. Donec eget arcu quis neque vulputate tempor. Etiam tincidunt scelerisque justo non tincidunt. Proin tincidunt mi non sapien eleifend vulputate. Ut varius libero et lectus vulputate sodales. Integer blandit erat nec quam mollis mattis. In semper dictum finibus. Vestibulum sed dictum sapien, sed accumsan magna. Vestibulum sodales elementum leo sed cursus. Curabitur sit amet semper odio. Curabitur ultricies lacus risus, ac suscipit purus vulputate sit amet. Integer porttitor, velit at feugiat volutpat, metus ligula rhoncus est, vel porttitor sem est quis odio. Donec eget porttitor orci, nec mattis dolor. Aliquam eget scelerisque nulla, quis aliquet augue. Vivamus volutpat aliquet massa, vel egestas dui ornare vel. Donec euismod neque non sollicitudin sodales. Ut quis lorem nibh. Praesent rhoncus libero aliquet interdum varius. Phasellus aliquet diam eget lectus dictum, vel porttitor turpis suscipit. Ut cursus sapien nec tristique tincidunt. Integer semper facilisis imperdiet. Aliquam eleifend a magna in congue. Vivamus quis orci scelerisque, finibus arcu eu, lacinia turpis. Donec at ultricies nulla. Quisque eget gravida sem, viverra dapibus ipsum.
            </div>
            <div class="px-2" x-collapse x-cloak x-show="activeTab === 4">
                <h2 class="font-poppinsBlack m-2 text-2xl">Política de cookies</h2>
                Sed eget lacus tincidunt, ornare mauris vitae, ullamcorper tellus. Vestibulum mollis ante vel tellus commodo pretium. Nulla vel blandit nisl, a sodales augue. Quisque porttitor in justo rutrum scelerisque. Donec rutrum est eros, eget laoreet eros placerat quis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris sit amet feugiat leo. Donec imperdiet blandit quam quis porta. Integer sem orci, tincidunt non sem at, interdum pulvinar risus. Cras tempor mollis massa, vel sodales felis pellentesque nec. In eu mauris interdum, laoreet ipsum vel, sodales dolor. Quisque luctus sapien nisi, at consectetur urna rhoncus in. Etiam suscipit eros vestibulum sollicitudin lobortis. Donec sed dui sit amet neque interdum vulputate in vel mi. Cras eleifend lectus et pulvinar finibus. Fusce vestibulum purus id sagittis feugiat. Nunc ultrices dignissim felis, nec pharetra tellus hendrerit ac. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur sit amet nunc at odio mollis venenatis. Morbi porttitor felis vel mi eleifend, vel tincidunt odio semper. Vestibulum ornare tempus augue, in bibendum nibh fringilla ut. Nunc mollis sollicitudin nulla, eget pellentesque purus elementum ac. Donec laoreet massa dui, ut semper libero rutrum pulvinar. Maecenas ut imperdiet nisl, vel mattis nulla. Integer interdum condimentum placerat. Sed consectetur condimentum eros, at porttitor orci scelerisque id. Duis venenatis eros nec aliquam luctus. Fusce nec nisi finibus felis dignissim consectetur. Proin sed orci nibh. Praesent justo nibh, rutrum vitae magna molestie, hendrerit vestibulum neque. Pellentesque ornare sit amet nisl at porta. Nunc quis felis purus. Nam accumsan purus ac tristique lobortis. Praesent tincidunt pulvinar elementum. Nullam efficitur fringilla sagittis. Morbi varius porttitor fermentum. Praesent fermentum, erat semper gravida volutpat, sem mi condimentum est, ac scelerisque massa orci ac elit. Nunc ullamcorper pellentesque efficitur. Mauris vel tellus ut massa dapibus tempor congue in massa. Phasellus ut facilisis massa, eu egestas tortor. Donec sit amet erat neque. Sed eu velit aliquet, sagittis lectus id, semper ipsum. Fusce turpis orci, pharetra eget euismod ut, viverra ut purus. Nullam faucibus nulla erat, id facilisis lectus tristique nec. Pellentesque scelerisque tincidunt ex, sed egestas dui mattis vitae. Nunc congue purus vitae nisl fermentum pulvinar. Pellentesque hendrerit nisl in est tempor, eget eleifend lacus fermentum. Pellentesque faucibus quam tristique orci placerat, eget iaculis nisi pellentesque. Donec tincidunt interdum ligula vitae ornare. Sed magna purus, pharetra id rutrum non, pellentesque id dui. Donec pellentesque neque tristique purus sodales, porta pharetra arcu eleifend. Nulla a sagittis nunc. Praesent maximus urna at condimentum ullamcorper. Pellentesque in libero tortor. Nullam dignissim leo nec dictum tempus.
            </div>
        </div>
    </div>

    @push('scripts')
        <script>
            console.log('Hola desde la protectora')
        </script>
    @endpush
</x-main-layout>
